import json

dct = {
    "person": "一个人",
    "event": "事件",
    "organization": "组织",
    "location": "地点",
    "living_thing": "活物",
    "music": "音乐",
    "building": "建筑",
    "art": "艺术作品",
    "written_work": "文学作品",
    "broadcast_program": "广播节目",
    "product": "产品",
    "astral_body": "天体",
    "transportation": "交通方式",
    "game": "游戏",
    "government": "政府",
    "geography": "地理实体",
    "military": "军事实体",
    "chemistry": "化学品",
    "software": "软件",
    "people": "人群",
    "disease": "疾病",
    "language": "语言",
    "play": "戏剧",
    "law": "法律",
    "medicine": "药物",
    "award": "奖项",
    "title": "头衔",
    "government_agency": "政府部门",
    "internet": "互联网",
    "body_part": "身体部分",
    "food": "食物",
    "livingthing": "活物",
    "train": "火车",
    "broadcast_network": "广播网络",
    "rail": "铁路",
    "metropolitan_transit": "城市交通",
    "computer": "计算机",
    "god": "神灵",
    "biology": "生物",
    "finance": "金融",
    "time": "事件",
    "park": "公园",
    "news_agency": "新闻社",
    "religion": "宗教",
    "education": "教育",
    "newspaper": "报纸",
    "transit": "换乘",
    "visual_art": "视觉艺术",
    "broadcast": "广播",
    "thing": "事物"
}

lst = dct.keys()
print(sorted(list(lst)))